name: typed_event_emitter
description: Simple package to emit and control events
repository: https://github.com/Davenchy/event_emitter
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.1
